version: '3.8'

services:
  vault:
    image: hashicorp/vault
    container_name: 'vault-local'
    ports:
    - '8200:8200'
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http:127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file

volumes:
  vault_data: